config/routes.rb
Molamp::Application.routes.draw do
  resource :account, :controller => 'users'
  resources :users
  resource :user_session
  
  resources :albums
  resources :search
  resources :faq
  resources :privacy
  resources :tos
  resources :about

  match 'account/social' => 'users#social'
  match 'account/claim' => 'users#claim'

  match 'artists' => 'artists#index'
  
  match 'artists/:id' => 'artists#show', :constraints => { :id => /[^\/]*/ } #:id => /[0-9a-zA-Z.&+%]+/
  match 'artists/:artist/:album' => 'albums#show', :constraints => { :artist => /[^\/]*/, :album => /[^\/]*/ } #:artist => /[0-9a-zA-Z.&+%'_-]+/, :album => %r{[0-9a-zA-Z.&':()+/!-_]+}i
  match 'artists/:artist/_/:track' => 'tracks#show', :constraints => { :artist => /[^\/]*/, :track => /[^\/]*/ }

  match 'auth/facebook' => 'auth#facebook'
  match 'auth/lastfm' => 'auth#lastfm'
  match 'auth/facebook/logout' => 'auth#logout_facebook'
  match 'auth/lastfm/logout' => 'auth#logout_lastfm'
  
  match 'ajax/scrobble_mode' => 'ajax#scrobble_mode'
  match 'ajax/activity_mode' => 'ajax#activity_mode'
  match 'ajax/scrobble'      => 'ajax#scrobble'
  match 'ajax/activity'      => 'ajax#activity'
  match 'ajax/activity/delete' => 'ajax#activity_delete'
  match 'ajax/image'         => 'ajax#get_image'
  match 'ajax/autocomplete'  => 'ajax#autocomplete'
  
  unless Rails.application.config.consider_all_requests_local
    match '*not_found' => 'errors#error_404'
  end

  root :to => "home#index"

end

app/views/shared/_about.html.erb
<div class="modal hide" id="aboutModal">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">×</button>
		<h3>About</h3>
	</div>
	<div class="modal-body">
		<p>The goal of this application is to allow people to listen to artists/bands tracklists and discover new ones for free.</p>
		<p>
		Made with <a href="http://twitter.github.com/bootstrap/" target="_blank">Bootstrap</a>. 
	    Powered by <a href="http://www.last.fm" target="_blank"><img src="/assets/lastfm_icon.png" alt="Last.fm" /></a>. 
	    <a href="http://stats.pingdom.com/bqylo5xy0dcj/679959" target="_blank">Service Status</a>.
	    </p>	    
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
	</div>
</div>

app/views/shared/_controls.html.erb
<% if params['controller'] === 'artists' or params['controller'] === 'albums' or params['controller'] === 'tracks' %>
<div class="player_controls">
	<div class="row-fluid">
		<div class="span3">
			<center>
				<a href="javascript:;" class="btn" id="previous_play">
					<i class="icon-backward"></i>
				</a>
				<a href="javascript:;" class="btn btn-large" id="toggle_play">
					<i class="icon-play"></i>
				</a>
				<a href="javascript:;" class="btn" id="next_play">
					<i class="icon-forward"></i>
				</a>
				
				&nbsp;&nbsp;&nbsp;&nbsp;
				<span id="current_time">00:00</span> / <span id="total_time">00:00</span>
			</center>
		</div>
		<div class="span7">
			<div id="progress_bar"></div>
		</div>
		<div class="span2">		
			<div class="progress_bar_volume_container">
				<div id="progress_bar_volume"></div>
			</div>	
			
			<a href="javascript:;" class="btn" id="toggle_volume">
				<i class="icon-volume-up"></i>
			</a>
			
			&nbsp;&nbsp;
			
			<a href="javascript:;" class="btn" id="toggle_fullscreen">
				<i class="icon-resize-full"></i>
			</a>
		</div>
	</div>
</div>
<% end %>

app/views/shared/_debug.html.erb
<% if Rails.env.development? && 1==0 %> 
	<div class="well">
	  <div id="debug">
	  	<%= link_to 'params', "javascript:$('#params_debug_info').toggle()" %> |
	  	<%= link_to 'env', "javascript:$('#env_debug_info').toggle()" %> |
	  	<%= link_to 'request', "javascript:$('#request_debug_info').toggle()" %> 
	  
	    <fieldset id="params_debug_info" class="debug_info" style="display: none">
	      <legend>params</legend>
	      <pre class="pre-scrollable">
	      	<%= debug(params) %>
	      </pre>
	    </fieldset>
	  
	    <fieldset id="env_debug_info" class="debug_info" style="display: none">
	      <legend>env</legend>
	      <pre class="pre-scrollable">
	      	<%= debug(request.env) %>
	      </pre>
	    </fieldset>
	    
	    <fieldset id="request_debug_info" class="debug_info" style="display: none">
	      <legend>request</legend>
	      <pre class="pre-scrollable">
	      	<%= debug(request) %>
	      </pre>
	    </fieldset>
	  </div>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="row-fluid" style="margin:10px 0;">
	<div class="span7">
		<div class="powered_by">
			Powered by <a href="http://www.last.fm" target="_blank">Last.fm</a> &amp; <a href="http://www.youtube.com" target="_blank">Youtube</a></p>
		</div>
	</div>
	
	<div class="span5">
		<div class="pull-right">
			<%= link_to image_tag('facebook_icon.png', :alt => 'Facebook', :size => '24x24'), 'http://www.facebook.com/molamp.net', :style => 'text-decoration:none', :rel => 'tooltip', :title => 'Like Molamp page on Facebook' %>
			<%= link_to image_tag('twitter_icon.png', :alt => 'Twitter', :size => '24x24'), 'http://www.twitter.com/molamp', :style => 'text-decoration:none',  :rel => 'tooltip', :title => 'Follow Molamp account on Twitter' %>
			<%= link_to image_tag('tumblr_icon.png', :alt => 'Tumblr', :size => '24x24'), 'http://molamp.tumblr.com', :style => 'text-decoration:none',  :rel => 'tooltip', :title => 'Follow Molamp blog on Tumblr' %>
			<!--<%= link_to image_tag('lastfm_icon_big.png', :alt => 'Last.fm', :size => '24x24'), 'http://www.last.fm/group/Molamp', :style => 'text-decoration:none', :rel => 'tooltip', :title => 'Join Molamp group on Last.fm' %>-->
			<%= link_to image_tag('//ssl.gstatic.com/images/icons/gplus-32.png', :alt => 'Google+', :size => '24x24'), 'https://plus.google.com/113049647993771497908?prsrc=3', :style => 'text-decoration:none', :rel => 'tooltip', :title => 'Follow Molamp page on Google+' %>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span7">
		<footer class="footer">
			<p>
				&copy; <%= Date.today.year %> Molamp <sup><span class="label label-info">beta</span></sup>. <small><%= ENV['rel'] %></small>
			</p>
		</footer>
	</div>
	<div class="span5">
		<ul class="unstyled pull-right footer_links">
			<li><a href="/about">About</a></li>
			<li><a href="/privacy">Privacy</a></li>
			<li><a href="/faq">FAQ</a></li>
			<li><a href="mailto:morion4000@gmail.com" target="_blank">Contact</a></li>
			<li><a href="https://status.molamp.com" target="_blank">Service Status</a></li>
		</ul>
	</div>
</div>

app/views/shared/_head.html.erb
<% if content_for?(:head) %>
<%= yield(:head) %>
<% else %>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
<% end %>

<% if content_for?(:meta) %>
<%= yield(:meta) %>
<% else %>
	<meta property="fb:app_id" content="<%= ENV['FACEBOOK_API_KEY'].to_s %>" /> 
	<meta property="og:type" content="website" />
	<meta property="og:url" content="http://www.molamp.net" /> 
	<meta property="og:image" content="http://www.molamp.net/assets/screenshot1.png" />
	<meta property="og:title" content="Molamp - Discover your music" />
	<meta property="og:description" content="A music search, play and suggestion mashup. Discover and rediscover a lot of great music." />
<% end %>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="author" content="Ionut Moraru" />
	<meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Molamp is a music search, play and suggestion mashup. Discover and rediscover a lot of great music.' %>" />
	<title><%= content_for?(:title) ? yield(:title) : 'Molamp - Discover your music' %></title>
	<script>
	    var _errs=["5104fcbc60dbfe3441000012"];(function(a,b){a.onerror=function(){_errs.push(arguments)};
	    var d=function(){var a=b.createElement("script"),c=b.getElementsByTagName("script")[0];
	    a.src="//d15qhc0lu1ghnk.cloudfront.net/beacon.js";a.async=!0;
	    c.parentNode.insertBefore(a,c)};a.addEventListener?a.addEventListener("load",d,!1):
	    a.attachEvent("onload",d)})(window,document);
	</script>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon" id="favicon" />
	<link rel="author" href="/humans.txt" />
	<%= render :partial => 'shared/widgets/googleanalytics' %>
</head>

app/views/shared/_header.html.erb
<%= render :partial => 'shared/menu' %>
<%= render :partial => 'shared/messages' %>

app/views/shared/_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to image_tag('logo_123x35.png', :alt => 'Logo', :size => '123x35'), root_path, :class => 'brand' %>
      <div class="nav-collapse">
        <ul class="nav">
        	<li><a href="http://blog.molamp.net">Blog</a></li>
        	<% unless logged_in? %>
        		<li class="divider-vertical"></li>
          		<li><a href="<%= new_user_session_path %>">Log In</a></li>
          		<li><a href="/account/new">Sign Up</a></li>
          	<% end %>
        </ul>
        <% if logged_in? %>
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>
          <li class="dropdown">
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', account_path %></li>
              <li><%= link_to 'Social', account_social_path %></li> 
              <li class="divider"></li>
              <li><%= link_to 'Logout', user_session_path, :method => :delete, :confirm => 'Are you sure you want to logout?' %></li>
            </ul>
          </li>
        </ul>
        <% end %>
        <form class="navbar-search pull-right" action="/search">
          <input type="hidden" name="w" value="generic" />
          <input type="text" name="q" class="search-query span2" autocomplete="off" placeholder="Search" id="generic_search">
        </form>
      </div><!-- /.nav-collapse -->
    </div>
  </div><!-- /navbar-inner -->
  
  <div class="ajax-spinner" style="margin-top:-20px;"></div>
</div>

app/views/shared/_messages.html.erb
<% if flash[:notice] %>
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <strong>Hurray!</strong> <%= flash[:notice] %>
</div>
<% end %>

<% if logged_in? and not current_user.claimed and controller.controller_name == 'users' and controller.action_name != 'claim' %>
	<div class="alert alert-info">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <strong>Unclaimed!</strong> You account is unclaimed. <%= link_to 'Click here to claim it', account_claim_path %>.
	</div>
<% end %>

<% if 0 == 1 %>
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <strong>Warning!</strong> We are experiencing some problems with the YouTube player API at the moment. The tracks are not buffering properly.
</div>
<% end %>

app/views/shared/_modals.html.erb
<div class="modal hide" id="confirmModal">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">×</button>
		<h3>Are you sure you want to leave the page?</h3>
	</div>
	<div class="modal-body">
		<p>You are watching a video right now. Leaving the page will stop the video.</p>	    
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Cancel</a>
		<a href="#" class="btn btn-primary" id="leave_url">Leave page</a>
	</div>
</div>